export const ROUTES = {
  root: '/',
  initial: 'init',
  login: 'login',
  appRoot: 'app/',
  dashboard: 'dashboard',
  dailyEntries: 'dailyEntries',
  register: 'register',
  forgot: 'forgot',
  foods: 'foods',
  admin: 'admin',
  more: 'more',
  plan: 'plan',
  profile: 'profile',
  appSettings: 'appSettings',
  termsAndConditions: 'termsAndConditions',
  faq: 'faq',
}
